{{- if .Values.backup.enable }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "esdb.fullname" . }}-backup-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "esdb.labels" . | nindent 4 }}
data:
  'config.json': |
    {{- include "backup.config" . | fromYaml | toPrettyJson | nindent 4 }}
{{- end }}

