apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "esdb.fullname" $}}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "esdb.labels" . | nindent 4 }}
data:
# Setup config, generate gossip seeds & add custom config
# This file will become the YAML configuration file for eventstore
{{- range $i, $e := until (.Values.deployment.clusterSize | int) }}
  '{{ include "esdb.fullname" $}}-{{ $i }}': |
    ExtIp: 0.0.0.0
    IntIp: 0.0.0.0

    Db: /data/db
    Log: /data/logs

    {{ if $.Values.deployment.logs.persist }}
    DisableLogFile: false
    {{- else }}
    DisableLogFile: true
    {{- end }}
    
    ClusterSize: {{ $.Values.deployment.clusterSize }}
    TrustedRootCertificatesPath: /certs/ca
    CertificateFile: /certs/node/{{ include "esdb.fullname" $}}-{{ $i }}.crt
    CertificatePrivateKeyFile: /certs/node/{{ include "esdb.fullname" $}}-{{ $i }}.key
    
    AdvertiseHostToClientAs: {{ (index $.Values.deployment.hosts ($i | toString)) }}

    IntHostAdvertiseAs: {{ include "esdb.fullname" $ }}-{{ $i }}
    ExtHostAdvertiseAs: {{ include "esdb.fullname" $ }}-{{ $i }}
    
    {{- $gossipSeeds := list}}
    {{- range $iInner, $eInner := until ($.Values.deployment.clusterSize | int) }}
    {{- if ne $iInner $i }}
      {{- $gossipSeeds = append $gossipSeeds (print (include "esdb.fullname" $) "-" $iInner ":2113") }}
    {{- end }}
    {{- end }}
    
    DiscoverViaDns: false
    GossipSeed: {{ $gossipSeeds | join "," }}
    
    AdvertiseHttpPortToClientAs: 443
    
    {{/*Shared config*/}}
    {{- toYaml $.Values.deployment.config.shared | nindent 4}}

    {{/* Node config*/}}
    {{- with index $.Values.deployment.config ($i | toString) }}
    {{- toYaml . | nindent 4}}
    {{- end }}

{{- end}}

