{{range $i, $e := until (.Values.deployment.clusterSize | int) }} 
apiVersion: v1
kind: Service
metadata:
  name: {{ include "esdb.fullname" $}}-{{ $i | toString }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "esdb.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp
      port: 1113
      protocol: TCP
      targetPort: tcp
    - name: grpcs
      port: 2113
      protocol: TCP
      targetPort: grpcs
  
  selector:
    {{- include "esdb.labels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "esdb.fullname" $}}-{{ $i | toString }}
    app.kubernetes.io/component: cluster
---
{{end}}