apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "esdb.fullname" . }}-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "esdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  serviceName: {{ include "esdb.fullname" .}}-cluster
  selector:
    matchLabels:
      {{- include "esdb.labels" . | nindent 6 }}
      app.kubernetes.io/component: cluster
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  replicas: {{ .Values.deployment.clusterSize }}
  template:
    metadata:
      labels:
        {{- include "esdb.labels" . | nindent 8 }}
        app.kubernetes.io/component: cluster
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end}}
    spec:
      serviceAccountName: {{ include "esdb.serviceAccountName" . }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: esdb
          image: '{{ .Values.deployment.esdb.image.repository }}:{{ .Values.deployment.esdb.image.tag | default (print .Chart.AppVersion "-bionic") }}'
          imagePullPolicy: {{ .Values.deployment.esdb.image.pullPolicy }}
          {{- with .Values.deployment.esdb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{end}}
          env:
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # Load the correct config (generated in config.yaml)
          args: [ '--config=/config/$(NODE)' ]
          ports:
            - containerPort: 1113
              name: tcp
              protocol: TCP
            - containerPort: 2113
              name: gossip
              protocol: TCP
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /certs/node
              name: node-certs
            - mountPath: /certs/ca
              name: ca-certs
            - mountPath: /config
              name: config
            - mountPath: /data/db
              name: data
            - mountPath: /data/log
              name: logs

          # The /health/live endpoint fails when the cluster is invalid
          # So we need to give the node time to join the cluster
          livenessProbe:
            exec:
              command: ['curl', 'https://localhost:2113/health/live', '--fail', '--silent', '--cacert', '/certs/ca/ca.crt']
            failureThreshold: {{ .Values.deployment.esdb.liveness.failureThreshold }}
            periodSeconds: {{ .Values.deployment.esdb.liveness.periodSeconds }}
              
          # No readiness probe is defined, because the clients will determine the best node
          # Even if the node is not ready, it should still be exposed to the clients
          # This may need revisiting however
            
        - name: proxy
          image: {{ .Values.deployment.proxy.image.repository}}:{{.Values.deployment.proxy.image.tag }}
          imagePullPolicy: {{ .Values.deployment.proxy.image.imagePullPolicy }}
          {{- with .Values.deployment.proxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          env:
          {{- range $i, $e := until (.Values.deployment.clusterSize | int) }}
            - name: PROXY_EventStore__{{$i}}__Host
              value: {{ index $.Values.deployment.hosts ($i | toString) }}
          {{- end}}
          ports:
            - containerPort: 80
              protocol: TCP
              name: http2
            - containerPort: 90
              protocol: TCP
              name: http1
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /certs/ca
              name: ca-certs
          livenessProbe:
            httpGet:
              port: http1
              path: /healthz/live

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}  
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}

      restartPolicy: Always
      
      volumes:
        - name: config
          configMap:
            name: {{ include "esdb.fullname" $}}-config
            defaultMode: 0440
        - name: node-certs
          secret:
            secretName: {{ include "esdb.fullname" $}}-certs
            defaultMode: 0440
        - name: ca-certs
          secret:
            secretName: {{ include "esdb.fullname" $}}-certs
            defaultMode: 0440
            items:
              - key: ca.crt
                path: ca.crt
              - key: ca.key
                path: ca.key
        {{- if not .Values.deployment.logs.persist }}
        - name: logs
          emptyDir: {}
        {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "esdb.labels" . | nindent 10 }}
          app.kubernetes.io/component: cluster
        {{- with .Values.deployment.storage.annotations }}
        annotations:
          {{ . | toYaml | nindent 10 }}
        {{- end }}
      spec:
        storageClassName: {{ .Values.deployment.storage.class }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.deployment.storage.size }}
  {{- if .Values.deployment.logs.persist }}
    - metadata:
        name: logs
        labels:
          {{- include "esdb.labels" . | nindent 10 }}
          app.kubernetes.io/component: cluster
        {{- with .Values.deployment.logs.storage.annotations }}
        annotations:
          {{ . | toYaml | nindent 10 }}
        {{- end }}
      spec:
        storageClassName: {{ .Values.deployment.logs.storage.class }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.deployment.logs.storage.size }}
  {{- end }}